# Generated by Django 4.1.1 on 2022-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
